/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author hp
 */
public class EncounterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EncounterJPanel
     */
    public EncounterJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEncPatientPhn = new javax.swing.JLabel();
        lblEncHos = new javax.swing.JLabel();
        txtEncPatientPhn = new javax.swing.JTextField();
        txtEncPatientId = new javax.swing.JTextField();
        lblEncHosId = new javax.swing.JLabel();
        txtEncHos = new javax.swing.JTextField();
        lblEncPatientId = new javax.swing.JLabel();
        txtEncHosId = new javax.swing.JTextField();
        txtEncPatientName = new javax.swing.JTextField();
        lblEncPatientName = new javax.swing.JLabel();
        lblEncounterRecordsTitle = new javax.swing.JLabel();
        lblEncDoc = new javax.swing.JLabel();
        lblEncTemp = new javax.swing.JLabel();
        lblEncBloodPressure = new javax.swing.JLabel();
        btnAddEncounter = new javax.swing.JButton();
        txtEncDoc = new javax.swing.JTextField();
        txtEncTemp = new javax.swing.JTextField();
        txtEncBloodPressure = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPatientDetails = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblSearchPatientId = new javax.swing.JLabel();
        txtPatientId = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1300, 700));

        lblEncPatientPhn.setText("Patient Phone:");

        lblEncHos.setText("Hospital:");

        txtEncPatientPhn.setEnabled(false);

        txtEncPatientId.setEnabled(false);

        lblEncHosId.setText("Hospital ID:");

        txtEncHos.setEnabled(false);

        lblEncPatientId.setText("Patient ID:");

        txtEncHosId.setEnabled(false);

        txtEncPatientName.setEnabled(false);

        lblEncPatientName.setText("Patient Name:");

        lblEncounterRecordsTitle.setText("Encounter Records");

        lblEncDoc.setText("Doctor:");

        lblEncTemp.setText("Temperature:");

        lblEncBloodPressure.setText("Blood Pressure:");

        btnAddEncounter.setText("Add");

        txtEncDoc.setEnabled(false);

        tblPatientDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "TimeStamp", "Temperature", "Blood Pressure"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblPatientDetails);

        jLabel1.setText("Get the records of patient");

        lblSearchPatientId.setText("Patient ID:");

        btnSearch.setText("Search");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEncPatientId)
                    .addComponent(lblEncPatientName)
                    .addComponent(lblEncPatientPhn)
                    .addComponent(lblEncHos)
                    .addComponent(lblEncHosId)
                    .addComponent(lblEncDoc)
                    .addComponent(lblEncTemp)
                    .addComponent(lblEncBloodPressure))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEncPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEncPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEncPatientPhn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEncHos, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEncHosId, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddEncounter)
                    .addComponent(txtEncDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEncTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEncBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(lblEncounterRecordsTitle)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(85, 85, 85)
                                .addComponent(lblSearchPatientId)
                                .addGap(18, 18, 18)
                                .addComponent(txtPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120)
                                .addComponent(btnSearch)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 937, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtEncPatientId, txtPatientId});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblEncounterRecordsTitle)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblSearchPatientId)
                    .addComponent(txtPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEncPatientId)
                            .addComponent(txtEncPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEncPatientName)
                            .addComponent(txtEncPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEncPatientPhn)
                            .addComponent(txtEncPatientPhn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEncHos)
                            .addComponent(txtEncHos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEncHosId)
                            .addComponent(txtEncHosId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEncDoc)
                            .addComponent(txtEncDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEncTemp)
                            .addComponent(txtEncTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEncBloodPressure)
                            .addComponent(txtEncBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAddEncounter))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEncounter;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEncBloodPressure;
    private javax.swing.JLabel lblEncDoc;
    private javax.swing.JLabel lblEncHos;
    private javax.swing.JLabel lblEncHosId;
    private javax.swing.JLabel lblEncPatientId;
    private javax.swing.JLabel lblEncPatientName;
    private javax.swing.JLabel lblEncPatientPhn;
    private javax.swing.JLabel lblEncTemp;
    private javax.swing.JLabel lblEncounterRecordsTitle;
    private javax.swing.JLabel lblSearchPatientId;
    private javax.swing.JTable tblPatientDetails;
    private javax.swing.JTextField txtEncBloodPressure;
    private javax.swing.JTextField txtEncDoc;
    private javax.swing.JTextField txtEncHos;
    private javax.swing.JTextField txtEncHosId;
    private javax.swing.JTextField txtEncPatientId;
    private javax.swing.JTextField txtEncPatientName;
    private javax.swing.JTextField txtEncPatientPhn;
    private javax.swing.JTextField txtEncTemp;
    private javax.swing.JTextField txtPatientId;
    // End of variables declaration//GEN-END:variables
}
