/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author hp
 */
public class EncounterHistoryPatient extends javax.swing.JPanel {

    /**
     * Creates new form EncounterHistoryPatient
     */
    public EncounterHistoryPatient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblEncPatientPhn = new javax.swing.JLabel();
        lblEncHos = new javax.swing.JLabel();
        txtEncPatientPhn = new javax.swing.JTextField();
        txtEncPatientId = new javax.swing.JTextField();
        lblEncHosId = new javax.swing.JLabel();
        txtEncHos = new javax.swing.JTextField();
        lblEncPatientId = new javax.swing.JLabel();
        txtEncHosId = new javax.swing.JTextField();
        txtEncPatientName = new javax.swing.JTextField();
        lblEncPatientName = new javax.swing.JLabel();
        lblEncounterRecordsTitle = new javax.swing.JLabel();
        lblEncDoc = new javax.swing.JLabel();
        txtEncDoc = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPatientEncDetails = new javax.swing.JTable();
        lblPatientAddr = new javax.swing.JLabel();
        txtPatientAddr = new javax.swing.JTextField();
        txtPatientPincode = new javax.swing.JTextField();
        lblPatientPincode = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1300, 700));

        jPanel1.setMaximumSize(new java.awt.Dimension(1300, 700));

        lblEncPatientPhn.setText("Patient Phone:");

        lblEncHos.setText("Hospital:");

        txtEncPatientPhn.setEnabled(false);

        txtEncPatientId.setEnabled(false);

        lblEncHosId.setText("Hospital ID:");

        txtEncHos.setEnabled(false);

        lblEncPatientId.setText("Patient ID:");

        txtEncHosId.setEnabled(false);

        txtEncPatientName.setEnabled(false);

        lblEncPatientName.setText("Patient Name:");

        lblEncounterRecordsTitle.setText("Check Your Encounter Records");

        lblEncDoc.setText("Doctor:");

        txtEncDoc.setEnabled(false);

        tblPatientEncDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "TimeStamp", "Temperature", "Blood Pressure"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblPatientEncDetails);

        lblPatientAddr.setText("Patient House:");

        txtPatientAddr.setEnabled(false);

        txtPatientPincode.setEnabled(false);

        lblPatientPincode.setText("Patient Pincode:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEncPatientId)
                    .addComponent(lblEncPatientName)
                    .addComponent(lblEncPatientPhn)
                    .addComponent(lblEncHos)
                    .addComponent(lblEncHosId)
                    .addComponent(lblEncDoc)
                    .addComponent(lblPatientAddr)
                    .addComponent(lblPatientPincode))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPatientPincode, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(txtPatientAddr)
                    .addComponent(txtEncPatientId)
                    .addComponent(txtEncPatientName)
                    .addComponent(txtEncPatientPhn)
                    .addComponent(txtEncHos)
                    .addComponent(txtEncHosId)
                    .addComponent(txtEncDoc))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(lblEncounterRecordsTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 941, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblEncounterRecordsTitle)
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEncPatientId)
                            .addComponent(txtEncPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEncPatientName)
                            .addComponent(txtEncPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEncPatientPhn)
                            .addComponent(txtEncPatientPhn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEncHos)
                            .addComponent(txtEncHos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEncHosId)
                            .addComponent(txtEncHosId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEncDoc)
                            .addComponent(txtEncDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatientAddr)
                            .addComponent(txtPatientAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPatientPincode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPatientPincode)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEncDoc;
    private javax.swing.JLabel lblEncHos;
    private javax.swing.JLabel lblEncHosId;
    private javax.swing.JLabel lblEncPatientId;
    private javax.swing.JLabel lblEncPatientName;
    private javax.swing.JLabel lblEncPatientPhn;
    private javax.swing.JLabel lblEncounterRecordsTitle;
    private javax.swing.JLabel lblPatientAddr;
    private javax.swing.JLabel lblPatientPincode;
    private javax.swing.JTable tblPatientEncDetails;
    private javax.swing.JTextField txtEncDoc;
    private javax.swing.JTextField txtEncHos;
    private javax.swing.JTextField txtEncHosId;
    private javax.swing.JTextField txtEncPatientId;
    private javax.swing.JTextField txtEncPatientName;
    private javax.swing.JTextField txtEncPatientPhn;
    private javax.swing.JTextField txtPatientAddr;
    private javax.swing.JTextField txtPatientPincode;
    // End of variables declaration//GEN-END:variables
}
