/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import entities.Hospital;
import entities.NewPerson;
import javax.swing.JOptionPane;
import models.DataStorageClass;

/**
 *
 * @author rinki
 */
public class LoginScreen extends javax.swing.JFrame {

    /**
     * Creates new form HomeScreen
     */
    public LoginScreen() {
        //Uncomment initcomments later
        initComponents();
//           dispose();
//           this.setVisible(false);
//           new SuperAdminDashboardScreen().setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Login_Screen_Login_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        LoginScreen_username_textfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LoginScreen_password_textfield = new javax.swing.JPasswordField();
        Login_Screen_Register_Button = new javax.swing.JButton();
        cmbRoleBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setForeground(new java.awt.Color(255, 204, 204));
        setMinimumSize(new java.awt.Dimension(1024, 576));

        Login_Screen_Login_Button.setBackground(new java.awt.Color(204, 204, 255));
        Login_Screen_Login_Button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Login_Screen_Login_Button.setText("LOGIN");
        Login_Screen_Login_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_Screen_Login_ButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Username");

        LoginScreen_username_textfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoginScreen_username_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginScreen_username_textfieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Password");

        LoginScreen_password_textfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Login_Screen_Register_Button.setBackground(new java.awt.Color(204, 204, 255));
        Login_Screen_Register_Button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Login_Screen_Register_Button.setText("REGISTER");
        Login_Screen_Register_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_Screen_Register_ButtonActionPerformed(evt);
            }
        });

        cmbRoleBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----Please Select-----", "System Admin", "Doctor", "Patient", "Person", "Community Admin", "Hospital Admin" }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Role");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbRoleBox, 0, 175, Short.MAX_VALUE)
                            .addComponent(LoginScreen_password_textfield)
                            .addComponent(LoginScreen_username_textfield)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(Login_Screen_Register_Button)
                        .addGap(45, 45, 45)
                        .addComponent(Login_Screen_Login_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginScreen_username_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LoginScreen_password_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbRoleBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login_Screen_Login_Button)
                    .addComponent(Login_Screen_Register_Button))
                .addGap(64, 64, 64))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hospital Management System");
        jLabel3.setAutoscrolls(true);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(209, 209, 209))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(336, 336, 336))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginScreen_username_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginScreen_username_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginScreen_username_textfieldActionPerformed

    private void Login_Screen_Login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_Screen_Login_ButtonActionPerformed
        // TODO add your handling code here:
        String username = LoginScreen_username_textfield.getText().trim();
        String password = new String(LoginScreen_password_textfield.getPassword());
        System.out.println("username " + username + " password " + password);
        
        NewPerson communityUser = new NewPerson();
        communityUser = new NewPerson();
        communityUser.setUuid(DataStorageClass.generateUUID());
        communityUser.setId("boston_admin");
        communityUser.setRole("COMMUNITY_ADMIN");
        communityUser.setPassword("patanahi");
        DataStorageClass.userArrayList.add(communityUser);
        
        communityUser = new NewPerson();
        communityUser.setUuid(DataStorageClass.generateUUID());
        communityUser.setId("mountain_view_admin");
        communityUser.setRole("COMMUNITY_ADMIN");
        communityUser.setPassword("patanahi");
        DataStorageClass.userArrayList.add(communityUser);
        
        
        
        if (username.equals("s") && password.equals("s")) {
            DataStorageClass.USERROLE = "SUPER_ADMIN";
            dispose();
            new SuperAdminDashboardScreen().setVisible(true);
        }else        if (!DataStorageClass.userArrayList.isEmpty()) {
            for (int i = 0; i < DataStorageClass.userArrayList.size(); i++) {
               System.out.println("username stored " + DataStorageClass.userArrayList.get(i).getId() + " password stored " + DataStorageClass.userArrayList.get(i).getPassword()
               + " role " + DataStorageClass.userArrayList.get(i).getRole() + " size " + DataStorageClass.userArrayList.size());
                if (DataStorageClass.userArrayList.get(i).getId().equals(username) && DataStorageClass.userArrayList.get(i).getPassword().equals(password)) {
                    NewPerson user = new NewPerson();
                    user = DataStorageClass.userArrayList.get(i);
                    switch (user.getRole()) {

                        case "HOSPITAL" -> {
                            DataStorageClass.USERROLE = "HOSPITAL";
                            DataStorageClass.USERID = user.getId();
                            dispose();
                            new SuperAdminDashboardScreen().setVisible(true);
                        }
                        
                        case "DOCTOR" -> {
                            DataStorageClass.USERROLE = "DOCTOR";
                            DataStorageClass.USERID = user.getId();
                            dispose();
                            new SuperAdminDashboardScreen().setVisible(true);
                        } 
                        case "PATIENT" -> {
                            DataStorageClass.USERROLE = "PATIENT";
                            DataStorageClass.USERID = user.getId();
                            dispose();
                            new SuperAdminDashboardScreen().setVisible(true);
                        }
                        case "COMMUNITY_ADMIN" -> {
                            DataStorageClass.USERROLE = "COMMUNITY_ADMIN";
                            DataStorageClass.USERID = user.getId();
                            dispose();
                            new SuperAdminDashboardScreen().setVisible(true);
                        }
                    }
i = DataStorageClass.userArrayList.size();
                }
                
            }

        } else {
            JOptionPane.showMessageDialog(null, "No Users Found. Register First");
        }

    }//GEN-LAST:event_Login_Screen_Login_ButtonActionPerformed

    private void Login_Screen_Register_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_Screen_Register_ButtonActionPerformed
        // TODO add your handling code here:
        DataStorageClass.USERROLE = "PERSON";
        dispose();
        new SuperAdminDashboardScreen().setVisible(true);
    }//GEN-LAST:event_Login_Screen_Register_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField LoginScreen_password_textfield;
    private javax.swing.JTextField LoginScreen_username_textfield;
    private javax.swing.JButton Login_Screen_Login_Button;
    private javax.swing.JButton Login_Screen_Register_Button;
    private javax.swing.JComboBox<String> cmbRoleBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
